FROM node:alpine

WORKDIR /app/

# Expose the port 3000
#EXPOSE 3000

# Set the default command to run when a container starts
#CMD ["node", "server.js"]

COPY package.json /app/
#COPY ./ /user/app

RUN npm install

COPY ./ /app/

CMD ["npm","run","start"]